[globals]

UI=app/views/
AUTOLOAD=app/
# app/blog/controller/|app/blog/model/|app/blog/view/|app/security/controller/|app/security/model/|app/security/view/|app/test/controller/|app/test/model/|app/test/view/|
