[globals]

UI=app/templates/
AUTOLOAD=app/

# каталог для сохранения пользовательских файлов
user_data_path="user_data"

# Путь до файла руководства пользователя
user_guide_path="doc/user_guide_2024.12.26.pdf"  